### ISSUE TITLE
Instruction screen in the begining of the experiment

### ISSUE THREAD

**Issue by rotemexp** [CallShaul/Experiment-control-panel-real-time-IR-VIS-video-recorder-with-external-monitor-video-player#3]
At the beginning of the experiment, the following text must be displayed. to start the experiment, the subject must click Continue / Next

בניסוי הבא תצפו בסרטונים שונים ולאחר כל סרטון תענו על כמה שאלות. במידה ומתעוררים בך רגשות שונים במהלך הצפייה נסה\י כמיטב יכולתך לחוות אותם ולא לחסום את עצמך מהחוויה. **שים\י לב!** קיימים הבדלים בין אנשים בתגובותיהם הרגשיות לתמונות. אנו מעוניינים לדעת כיצד **את\ה מרגיש\ה**. 
יש להגיב על פי ההרגשה בפועל ולא על פי מה שאנו מצפים שתרגיש\י, לא על פי מה את\ה מצפה מעצמך להרגיש ולא לפי מה שחשבת שנכון להרגיש.

I think we can combine it with the WarmUp function. meaning, during the warmup the instruction will appear and will remain until the warmup is over, unless the subject didnt press ok\continue. in this case the instructions will remain until the subject will press continue

**Comment by CallShaul** [comment]
Done. (You can send me a different docx / png file anytime to replace the intro message.

![image](https://user-images.githubusercontent.com/52006780/85327973-89705f00-b4d8-11ea-817a-2d83c3a437a8.png)
