### ISSUE TITLE
Demographic questions

### ISSUE THREAD

**Issue by rotemexp** [CallShaul/Experiment-control-panel-real-time-IR-VIS-video-recorder-with-external-monitor-video-player#4]
The following questions should be included in the experiment, when they should appear immediately after the instructions screen or at the end of the experiment, after all the videos.

מין - זכר \ נקבה. יש לכלול את שתי אופציות אלו בלבד, כאשר הנבדק מסמן את האופציה הרלוונטית. 

 גיל - טווח גילאים מ-18 עד 80 (לא סביר שיהיו לנו נבדקים מבוגרים אבל שתהיה את האופציה) יכול להיעשות על ידי טקסט חופשי (כאשר ניתן להשתמש רק בספרות) או על ידי בחירה מאופציות קיימות.

נטייה מינית - בחירה מתוך האופציות הבאות: 1. הטרוסקסואל 2. הומוסקסואל  3. ביסקסואל 4. אני מעדיפ\ה לא לענות.

**Comment by CallShaul** [comment]
Keep in mind there's no keyboard at the subjects experiment room, so either we add one, or we'll use a drop-down menu with all the options.

**Comment by CallShaul** [comment]
How's the layout ?

![image](https://user-images.githubusercontent.com/52006780/85330202-95f6b680-b4dc-11ea-8f91-cd216f11d47b.png)

**Comment by CallShaul** [comment]
Issue solved:

![image](https://user-images.githubusercontent.com/52006780/85410245-85435080-b56f-11ea-996d-a51c12561c2b.png)
