### ISSUE TITLE
Correcting the question about the emotional category

### ISSUE THREAD

**Issue by rotemexp** [CallShaul/Experiment-control-panel-real-time-IR-VIS-video-recorder-with-external-monitor-video-player#5]
יש לשנות את הניסוח של השאלה " באיזה מידה הסרטון גרם לך להרגיש אחד או יותר מהרגשות הבאים"    
 ל- " מהו הרגש הדומיננטי ביותר שחווית בעקבות הצפייה בסרטון" 

בנוסף, יש לשנות האופציות בצורה הבאה: במקום "ניטרלי\אף רגש" יופיע רק "ניטרלי". יש להוסיף אופציה נוספת "אף אחד מהרגשות הבאים" .

**Comment by CallShaul** [comment]
Done.
